spring:
  cloud:
    gateway:
      routes:
        - id: Annonce-Service
          uri: lb://Annonce-SERVICE
          predicates:
            - Path= /Annonce/**

        - id: Auth-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path= /auth/**





  application:
    name: gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


server:
  port: 8082