spring:
  cloud:
    gateway:
      routes:
        - id: API-SERVICE
          uri: lb://API-SERVICE
          predicates:
            - Path= /API/**

        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path= /auth/**





  application:
    name: gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


server:
  port: 8082