server:
  port: 8888

spring:
  application:
    name: "cloudgateway"
  cloud:
    gateway:
      global-cors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
